#
# Makefile
#  Rust cargo doesn't quite have the functionality we need yet so using
#  a very simple makefile to automate building.
#
# Targets:
#
#  clean - Cleans the build directories
#
# Example:
#  $ make clean
#

clean:
	cargo clean
