[package]
name = "rpi3fxproc"
version = "0.1.0"
authors = ["rhealy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
