[package]
name = "effects"
version = "0.1.0"
authors = ["Richard A. Healy <rahealy@users.noreply.github.com>"]
edition = "2018"

[dependencies]
# libm = "0.1.4"
# rustfft = "3.0.0"

[dependencies.peripherals]
path="../hardware/peripherals"

[dependencies.common]
path="../common"
