#
# Makefile
#
# Targets:
#
#  clean - Cleans the build directories
#
# Example:
#  $ make clean
#

#######################################################################
# Targets
#######################################################################

clean:
	cargo clean
